// Sanitized structural fixture. WorkBuddy appearance overrides come ONLY from CompiledTheme.css.
export type PreviewScene = "home" | "chat" | "dialog";
const base = `*{box-sizing:border-box}html,body,#root{margin:0;min-height:100%;font:14px/1.55 'Segoe UI','Microsoft YaHei',sans-serif}button,input{font:inherit}button{border:1px solid #ccd3d8;background:transparent;padding:8px 12px;cursor:pointer}button:disabled{cursor:not-allowed}input{width:100%;border:1px solid #ccd3d8;padding:10px}p{margin:8px 0}h1,h2,h3{margin:0}h1{font-size:27px}h2{font-size:18px}small{font-size:12px}.teams-container{display:flex;min-height:620px}.conversation-sidebar{width:188px;flex-shrink:0;padding:19px 12px;border-right:1px solid}.brand{font-size:17px;font-weight:700;margin-bottom:20px}.conversation-sidebar button{width:100%;text-align:left;margin-bottom:6px}.conversation-list{display:grid;gap:4px;margin-top:25px}.conversation-list small{padding:6px}.teams-content-wrapper{flex:1;min-width:0}.workbuddy-topbar{height:56px;display:flex;align-items:center;justify-content:space-between;padding:0 22px;border-bottom:1px solid}.main-content{min-height:564px}.wb-home-page{min-height:564px;padding:60px 30px}.welcome{max-width:650px;margin:auto}.categories{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.wb-home-composer__input-slot>section,.chat-container section{padding:14px;border:1px solid;}.composer-field{min-height:70px;outline:none}.composer-tools{display:flex;align-items:center;gap:12px;margin-top:8px}.composer-tools button:last-child{margin-left:auto}.quick-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:18px}.quick-grid button{text-align:left}.quick-grid small{display:block}.chat-container{min-height:564px;padding:24px}.messages{display:grid;gap:16px;margin-bottom:20px}.cb-assistant-message,.sample_userMessageBubble_v1{padding:15px;border:1px solid;}.user{margin-left:18%}.code{white-space:pre-wrap;padding:10px;border:1px solid;}.dialog-scene{position:relative;min-height:564px;padding:25px}.scrim{position:absolute;inset:0;background:#10182042;display:grid;place-items:center;padding:20px}[role=dialog]{width:min(380px,95%);padding:22px;border:1px solid;box-shadow:0 14px 45px #15231925}[role=dialog] label{display:grid;gap:8px;margin:18px 0}[role=dialog] footer{display:flex;justify-content:flex-end;gap:9px;margin-top:20px}[role=menu]{position:relative;width:180px;border:1px solid;padding:7px;z-index:1}[role=menuitem]{display:block;width:100%;border:0;text-align:left}.note{font-size:12px;margin-top:8px}@media(max-width:650px){.conversation-sidebar{width:136px}.wb-home-page{padding:30px 18px}.chat-container{padding:18px}.quick-grid{grid-template-columns:1fr}}`;
const gridBase = `.cb-markdown,section ._mainArea_fixture{background:#fff}.cb-markdown pre,.cb-markdown code{background:#f5f5f5}table{border-collapse:collapse;width:100%}th,td{padding:8px;border:1px solid #ddd}/* WorkBuddy 5.2.6 backing grid: keep this opaque baseline in the fixture. */.teams-container{display:block}._grid_fixture,._gridView_fixture{min-height:620px}._gridView_fixture{display:flex}._gridViewItem_fixture{background:#fafafa;min-width:0;flex:1}._gridViewItem_fixture:has(>.conversation-sidebar){flex:0 0 auto;display:flex}`;
const composer = `<section><div class="_mainArea_fixture"><div role="textbox" contenteditable="true" aria-label="示例输入框" class="composer-field" spellcheck="false">在这里检查输入框、文字和聚焦状态…</div><div class="composer-tools"><button type="button">＋</button><small>深度思考</small><span role="button" tabindex="0" class="_icon_fixture _large_fixture" aria-label="发送示例">↑</span></div></div></section>`;
const scenes: Record<PreviewScene, string> = {
  home: `<div class="wb-home-page"><div class="welcome"><small>WORKBUDDY · 示例工作台</small><h1>今天想做些什么？</h1><p>这是脱敏的界面样板，可检查主题的配色与层次。</p><div class="categories"><button class="conversation-list-tab-button" aria-selected="true">日常办公</button><button>代码开发</button><button>数据分析</button><button disabled>禁用状态</button></div><div class="wb-home-composer"><div class="wb-home-composer__input-slot">${composer}</div></div><div class="quick-grid"><button>文档处理<small>总结与润色</small></button><button>代码开发<small>分析与调试</small></button><button>数据分析<small>表格与图表</small></button></div></div></div>`,
  chat: `<div class="main-content--chat"><div class="chat-container"><div class="messages"><div class="cb-assistant-message"><div class="cb-markdown"><strong>检查消息区域的可读性</strong><p>正文、辅助文字、面板、边框和按钮均使用主题引擎生成的样式。</p><small>辅助信息 · 示例内容，不是真实聊天</small></div></div><div id="user-message-example" class="user"><div class="sample_userMessageBubble_v1">再看看背景、用户消息与输入框是否协调。</div></div><div class="cb-assistant-message"><div class="cb-markdown"><p>可以移动鼠标、按 Tab 或输入示例文字，检查交互状态。</p><blockquote>引文示例 <a href="#sample">参考链接</a></blockquote><table><thead><tr><th>项目</th><th>状态</th></tr></thead><tbody><tr><td>主题样例</td><td>仅本机</td></tr></tbody></table><pre class="code"><code>// 示例代码\nconst theme = "我的主题";</code></pre></div></div></div>${composer}</div></div>`,
  dialog: `<div class="main-content--chat dialog-scene"><h2>弹窗与菜单状态</h2><p>检查强面板、按钮和输入框。</p><div class="scrim"><div role="dialog" aria-label="示例主题设置"><h2>保存自定义主题</h2><label>主题名称<input value="我的图片主题" aria-label="示例主题名称"></label><div role="menu" aria-label="示例快捷菜单"><button role="menuitem">新建对话</button><button role="menuitem">主题设置</button><button role="menuitem" disabled>禁用菜单项</button></div><footer><button>取消</button><button class="cb-button--primary">确认</button></footer></div></div></div>`,
};
export function previewDocument(
  css: string,
  imageUrl: string,
  scene: PreviewScene,
) {
  const safeUrl =
    /^(data:image\/(png|jpeg|webp);base64,|https?:\/\/asset\.localhost\/|asset:\/\/localhost\/)/.test(
      imageUrl,
    )
      ? imageUrl
      : "";
  const asset = safeUrl.replace(/["<>\\\n\r]/g, "");
  const safeCss = css.replace(/<\/style/gi, "\\3c /style");
  return `<!doctype html><html class="codedrobe-host-workbuddy" lang="zh-CN"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'none'; style-src 'unsafe-inline'; img-src data: http://asset.localhost https://asset.localhost asset:; font-src 'none'; connect-src 'none'; form-action 'none'; base-uri 'none'"><style>${base}${gridBase}</style><style id="codedrobe-theme-style-workbuddy">${safeCss}</style><style>:root{--codedrobe-image-hero:url("${asset}")}</style></head><body><div id="root"><div class="teams-container"><div class="_grid_fixture"><div class="_gridView_fixture"><div class="_gridViewItem_fixture"><aside class="conversation-sidebar"><div class="brand">◈ WorkBuddy</div><button>＋ 新建对话</button><button class="conversation-list-tab-button" aria-selected="${scene === "home"}">工作台</button><button class="conversation-list-tab-button" aria-selected="${scene === "chat"}">对话</button><button>项目</button><div class="conversation-list"><small>最近对话 · 示例</small><button class="conversation-agent-card _selected_fixture" aria-current="page">项目需求讨论</button><button>周报内容整理</button></div><div class="conversation-sidebar-footer"><small>本机示例用户</small></div></aside></div><div class="_gridViewItem_fixture"><div class="teams-content-wrapper"><header class="workbuddy-topbar"><strong>${scene === "home" ? "工作台" : scene === "chat" ? "项目需求讨论" : "组件状态检查"}</strong><small>示例工作区</small></header><main class="teams-main-content main-content">${scenes[scene]}</main></div></div></div></div></div></div></body></html>`;
}
